### ISSUE TITLE
arrays not allowed in class constants

### ISSUE THREAD

**Issue by bassmo** [leytech/Leytech_PrototypeUpdate#5]
For php versions below 5.6 the array of available versions in  app\code\community\Leytech\PrototypeUpdate\Helper\Data.php  causes the fatal error.

Arrays are not allowed in class constants in 
 app\code\community\Leytech\PrototypeUpdate\Helper\Data.php on line 15

As the CONSTANT appears to only be used in the same script in the isVersionValid function, replacing this with a simple

public $validVersions =['1.7.1.0', '1.7.2.0', '1.7.3.0'];

and then

    public function isVersionValid($version) {
        if (in_array($version, $this->validVersions)) {
            return true;
        }
        return false;
    }

seems to do the trick

**Comment by bluec** [comment]
It is 2019. You should not be using a PHP version prior to 7.1 let alone prior to 5.6!

https://php.net/supported-versions.php

**Comment by bluec** [comment]
As an aside, it is declared as a const for good reason, and if you do need to replace it with a property then at least make the property private and not public!

**Comment by bassmo** [comment]
Try running that version of Magento in php 7.1+ - other than that I agree

**Comment by bluec** [comment]
There is official PHP 7.2 support for all Magento 1 versions going back to 1.9.2.0

https://magento.com/tech-resources/download#download2240

If you're running an older version of Magento than 1.9.2 then you should seriously consider upgrading. 1.9.2 was released 4 years ago.

**Comment by bassmo** [comment]
Yer we have 3 sites remaining on 1.9.1 - working on Magento 2 at the moment. Used your module to allow feefo reviews on them though - so still worked, thanks.

**Comment by bluec** [comment]
Glad it worked. I have found it works nicely but doesn't play well with some third-party extensions, notably Idev_OneStepCheckout.
